# .toolforge.yaml
type: webservice
runtime: node20
healthcheck_path: /api/health
memory: 512Mi
cpu: 0.5
replicas: 1
build:
  - echo "Building server..."
  - cd server && npm install && npm run build
  - echo "Building client..."
  - cd ../client && npm install && npm run build
start: npm start
